let firstname = "Maria";
firstname = "Jacky";
let nr1 = 12;
var nr2 = 8;
const PI = 3.14159;
let language = "JavaScript";
let message = `Let's learn ${language}`;
console.log(message);
let str = "Hello, what's your name? Is it \"Mike\"?";
console.log(str);
let str2 = 'Hello, what\'s your name? Is it "Mike"?';
console.log(str2);
let nrToStr = 6;
nrToStr = String(nrToStr);
console.log(nrToStr, typeof nrToStr);
let strToNr = "12";
strToNr = Number(strToNr);
console.log(strToNr, typeof strToNr);
let strToBool = "";
strToBool = Boolean(strToBool);
console.log(strToBool, typeof strToBool);
let nullToNr = null;
nullToNr = Number(nullToNr);
console.log("null", nullToNr, typeof nullToNr);
let strToNr2 = "";
strToNr = Number(strToNr);
console.log("empty string", strToNr, typeof strToNr);
let number1 = 12;
let result1 = number1 + nr2;
const a = 5;
const b = 10;
console.log(a > 0 && b > 0);
console.log(a == 5 && b == 4);
console.log(true ||false);
console.log(a == 3 || b == 10);
console.log(a == 3 || b == 7); 
